export interface Strategy {
  id: string;
  name: string;
  description: string;
  side: "attack" | "defense" | "both";
  difficulty: "easy" | "medium" | "hard" | "extreme";
  category: "fun" | "challenge" | "teamwork" | "meme" | "tactical";
  restrictions?: string[];
  tips?: string[];
}

export const strategies: Strategy[] = [
  // Attack Strategies
  {
    id: "rush-b",
    name: "Rush B",
    description: "No droning, no planning. Pick a random entry point and rush in as fast as possible. First 30 seconds only.",
    side: "attack",
    difficulty: "medium",
    category: "fun",
    restrictions: ["No droning allowed", "Must enter within 30 seconds"],
    tips: ["Coordinate with your team", "Bring flashbangs"],
  },
  {
    id: "silent-but-deadly",
    name: "Silent But Deadly",
    description: "Use only suppressed weapons. No callouts allowed - use pings only.",
    side: "attack",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Suppressed weapons only", "No voice comms - pings only"],
  },
  {
    id: "drone-army",
    name: "Drone Army",
    description: "Everyone must keep their drone alive. If your drone dies, you cannot enter the building until the last 30 seconds.",
    side: "attack",
    difficulty: "hard",
    category: "tactical",
    restrictions: ["Keep drone alive", "No entry if drone destroyed (until last 30s)"],
  },
  {
    id: "pistol-only",
    name: "Pistol Pete",
    description: "Secondary weapons only for the entire round. Show off your aim!",
    side: "both",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Pistols/secondaries only", "No gadget kills"],
  },
  {
    id: "no-kill-plant",
    name: "Pacifist Plant",
    description: "Plant the defuser without killing anyone. Injures are allowed but no confirms.",
    side: "attack",
    difficulty: "extreme",
    category: "challenge",
    restrictions: ["No kills allowed", "Injures OK but no confirms"],
    tips: ["Use smokes and flashes", "Coordinate distractions"],
  },
  {
    id: "shield-wall",
    name: "Shield Wall",
    description: "At least 2 players must bring shield operators. They lead every push.",
    side: "attack",
    difficulty: "medium",
    category: "teamwork",
    restrictions: ["Minimum 2 shield operators", "Shields must lead pushes"],
  },
  {
    id: "vertical-only",
    name: "Floor Is Lava",
    description: "Attack only from above or below. No same-floor gunfights until plant.",
    side: "attack",
    difficulty: "hard",
    category: "tactical",
    restrictions: ["Vertical play only", "No same-floor fights until plant"],
    tips: ["Bring Buck, Sledge, or Ash", "Learn floor layouts"],
  },
  {
    id: "one-drone-wonder",
    name: "One Drone Wonder",
    description: "The entire team shares ONE drone. Pass control between players.",
    side: "attack",
    difficulty: "hard",
    category: "teamwork",
    restrictions: ["Only 1 drone for the whole team", "Must share drone control"],
  },
  {
    id: "recruit-rush",
    name: "Recruit Rush",
    description: "Everyone plays Recruit. Pick M870 shotguns and rush site.",
    side: "attack",
    difficulty: "medium",
    category: "meme",
    restrictions: ["Recruit only", "M870 shotgun recommended"],
  },
  {
    id: "delayed-entry",
    name: "Fashionably Late",
    description: "Cannot enter the building until 1:30 remains on the clock.",
    side: "attack",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["No building entry until 1:30 left"],
    tips: ["Use drones extensively", "Plan your entry route"],
  },

  // Defense Strategies
  {
    id: "roam-or-die",
    name: "Roam or Die",
    description: "Everyone must roam. No one can be in the objective room until attackers plant.",
    side: "defense",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["No anchoring", "Must roam until plant"],
  },
  {
    id: "fortress",
    name: "Fortress",
    description: "Everyone stays on site. Maximum reinforcements and utility in objective.",
    side: "defense",
    difficulty: "easy",
    category: "tactical",
    restrictions: ["No roaming", "Everyone on site"],
    tips: ["Stack utility on chokepoints", "Crossfire setups"],
  },
  {
    id: "no-cams",
    name: "Blind Justice",
    description: "Cannot use any cameras (default or operator gadgets). Rely on sound only.",
    side: "defense",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["No camera usage", "Sound only"],
  },
  {
    id: "shotgun-troop",
    name: "Shotgun Troop",
    description: "Primary shotguns only. Create maximum rotation holes.",
    side: "defense",
    difficulty: "medium",
    category: "fun",
    restrictions: ["Shotgun primaries only"],
    tips: ["Create rotations and murder holes", "Hold tight angles"],
  },
  {
    id: "impact-artist",
    name: "Impact Artist",
    description: "Everyone brings impact grenades. Create a maze of rotation holes.",
    side: "defense",
    difficulty: "easy",
    category: "fun",
    restrictions: ["Impact grenades required"],
  },
  {
    id: "spawn-peek-squad",
    name: "Spawn Peek Squad",
    description: "At least 3 players must attempt spawn peeks at round start.",
    side: "defense",
    difficulty: "medium",
    category: "meme",
    restrictions: ["Minimum 3 spawn peekers"],
    tips: ["Know common spawn peek spots", "Have backup plan if it fails"],
  },
  {
    id: "basement-boys",
    name: "Basement Boys",
    description: "Set up your defense in the basement regardless of actual objective location.",
    side: "defense",
    difficulty: "extreme",
    category: "meme",
    restrictions: ["Defend from basement only"],
  },
  {
    id: "trap-house",
    name: "Trap House",
    description: "Maximum trap operators. Every doorway must have a trap.",
    side: "defense",
    difficulty: "medium",
    category: "tactical",
    restrictions: ["Trap operators only", "Cover all entrances"],
    tips: ["Kapkan, Frost, Lesion, Ela recommended"],
  },
  {
    id: "eco-round",
    name: "Eco Round",
    description: "Cannot use any utility or gadgets. Gun skill only.",
    side: "both",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["No gadgets", "No utility", "Guns only"],
  },
  {
    id: "musical-chairs",
    name: "Musical Chairs",
    description: "Every 30 seconds, all defenders must rotate to a new position.",
    side: "defense",
    difficulty: "extreme",
    category: "fun",
    restrictions: ["Rotate positions every 30 seconds"],
  },

  // Both Sides
  {
    id: "knife-fight",
    name: "Knife Fight",
    description: "First kill must be with melee. After that, guns are allowed.",
    side: "both",
    difficulty: "extreme",
    category: "meme",
    restrictions: ["First kill must be melee"],
  },
  {
    id: "hip-fire-heroes",
    name: "Hip Fire Heroes",
    description: "No aiming down sights allowed. Hip fire only.",
    side: "both",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["No ADS", "Hip fire only"],
    tips: ["Use laser sights", "Get close to enemies"],
  },
  {
    id: "flash-dance",
    name: "Flash Dance",
    description: "Must throw a flash/stun before every engagement.",
    side: "both",
    difficulty: "medium",
    category: "fun",
    restrictions: ["Flash before every fight"],
  },
  {
    id: "follow-the-leader",
    name: "Follow the Leader",
    description: "One player is the leader. Everyone else must follow within 5 meters at all times.",
    side: "both",
    difficulty: "medium",
    category: "teamwork",
    restrictions: ["Stay within 5m of leader", "Leader makes all calls"],
  },
  {
    id: "no-reinforcements",
    name: "Open House",
    description: "No reinforcements allowed. Soft walls only.",
    side: "defense",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["No reinforcing walls"],
  },
  {
    id: "role-reverse",
    name: "Role Reversal",
    description: "Attackers play slow and methodical. Defenders play aggressive and push out.",
    side: "both",
    difficulty: "medium",
    category: "fun",
    restrictions: ["Swap typical playstyles"],
  },
  {
    id: "callout-chaos",
    name: "Callout Chaos",
    description: "All callouts must be made using only colors and shapes. No room names.",
    side: "both",
    difficulty: "hard",
    category: "fun",
    restrictions: ["No proper callouts", "Colors and shapes only"],
  },
  {
    id: "headshots-only",
    name: "Headhunter",
    description: "Only headshot kills count. Body shot kills don't count toward your score.",
    side: "both",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Headshots only count"],
  },
  {
    id: "grenade-spam",
    name: "Explosive Personality",
    description: "Must use all grenades/C4/impacts before firing your weapon.",
    side: "both",
    difficulty: "medium",
    category: "fun",
    restrictions: ["Use all explosives first"],
  },
  {
    id: "360-kills",
    name: "360 No Scope",
    description: "Before each kill, you must do a 360 spin. Recorded kills only.",
    side: "both",
    difficulty: "extreme",
    category: "meme",
    restrictions: ["360 spin before every kill"],
  },

  // Additional Strategies (30 more)
  {
    id: "crouch-walk",
    name: "Tactical Crouching",
    description: "Must crouch walk the entire round. No standing or running allowed.",
    side: "both",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Crouch walk only", "No standing"],
    tips: ["Use the slower pace to aim better"],
  },
  {
    id: "one-mag",
    name: "One Mag Wonder",
    description: "You cannot reload. Use only the magazine you spawn with.",
    side: "both",
    difficulty: "extreme",
    category: "challenge",
    restrictions: ["No reloading", "Starting mag only"],
    tips: ["Make every shot count", "Use sidearm as backup"],
  },
  {
    id: "window-warrior",
    name: "Window Warrior",
    description: "Can only enter/exit through windows. No doors allowed.",
    side: "attack",
    difficulty: "hard",
    category: "fun",
    restrictions: ["Windows only", "No door usage"],
  },
  {
    id: "announcer",
    name: "The Announcer",
    description: "One player must commentate the entire round like a sports announcer.",
    side: "both",
    difficulty: "easy",
    category: "fun",
    restrictions: ["One dedicated commentator"],
    tips: ["Keep it entertaining", "Call out plays dramatically"],
  },
  {
    id: "protect-vip",
    name: "Protect the VIP",
    description: "One random player is the VIP. They cannot shoot. Team must protect them.",
    side: "both",
    difficulty: "hard",
    category: "teamwork",
    restrictions: ["VIP cannot use weapons", "VIP must survive"],
  },
  {
    id: "wrong-attachments",
    name: "Cursed Loadout",
    description: "Use the worst possible attachments on your guns. No sights, long barrel on SMGs, etc.",
    side: "both",
    difficulty: "medium",
    category: "meme",
    restrictions: ["Worst attachments only"],
  },
  {
    id: "last-alive-decides",
    name: "Last Alive Decides",
    description: "The last person alive from the previous round picks everyone's operator.",
    side: "both",
    difficulty: "easy",
    category: "fun",
    restrictions: ["Winner picks all operators"],
  },
  {
    id: "reverse-roles",
    name: "Opposite Day",
    description: "Support players must entry frag. Entry fraggers must support.",
    side: "attack",
    difficulty: "medium",
    category: "fun",
    restrictions: ["Swap your usual role"],
  },
  {
    id: "floor-is-lava-defense",
    name: "High Ground",
    description: "Defenders can only stand on furniture, counters, or deployable shields.",
    side: "defense",
    difficulty: "extreme",
    category: "meme",
    restrictions: ["No touching the floor"],
  },
  {
    id: "smoke-screen",
    name: "Smoke Screen",
    description: "Every player must bring smokes. Deploy all smokes before engaging.",
    side: "attack",
    difficulty: "medium",
    category: "tactical",
    restrictions: ["Smoke grenades required", "Use all before fighting"],
  },
  {
    id: "loud-and-proud",
    name: "Loud and Proud",
    description: "No suppressors. Must scream/yell when you see an enemy.",
    side: "both",
    difficulty: "easy",
    category: "fun",
    restrictions: ["No suppressors", "Verbal callouts required"],
  },
  {
    id: "backseat-gaming",
    name: "Backseat Gaming",
    description: "Dead teammates must give constant advice. Living players must follow it.",
    side: "both",
    difficulty: "medium",
    category: "teamwork",
    restrictions: ["Dead players give orders", "Living must obey"],
  },
  {
    id: "blitz-only",
    name: "Blitz Rush",
    description: "One player must play Blitz and lead every engagement with shield flashes.",
    side: "attack",
    difficulty: "medium",
    category: "tactical",
    restrictions: ["Blitz required", "Must lead pushes"],
  },
  {
    id: "nomad-trap",
    name: "Airjab Alley",
    description: "Nomad must use all airjabs in one doorway/hallway to create a bounce house.",
    side: "attack",
    difficulty: "easy",
    category: "meme",
    restrictions: ["Stack all airjabs in one spot"],
  },
  {
    id: "interrogation-hunter",
    name: "Interrogation Hunter",
    description: "Caveira must get at least one interrogation or the team loses (morally).",
    side: "defense",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Caveira required", "Must interrogate"],
  },
  {
    id: "monty-block",
    name: "Montagne Marathon",
    description: "Montagne must plant the defuser while fully extended. Team provides cover.",
    side: "attack",
    difficulty: "extreme",
    category: "challenge",
    restrictions: ["Montagne plants", "Shield must be extended"],
  },
  {
    id: "all-acog",
    name: "ACOG Army",
    description: "Everyone must use the highest magnification scope available on their weapon.",
    side: "both",
    difficulty: "medium",
    category: "challenge",
    restrictions: ["Highest zoom scopes only"],
  },
  {
    id: "all-holo",
    name: "Holo Heroes",
    description: "Everyone must use 1x holographic sights only.",
    side: "both",
    difficulty: "easy",
    category: "challenge",
    restrictions: ["1x holo sights only"],
  },
  {
    id: "random-sensitivity",
    name: "Sensitivity Roulette",
    description: "Randomize your sensitivity settings before the round.",
    side: "both",
    difficulty: "extreme",
    category: "meme",
    restrictions: ["Random sensitivity"],
    tips: ["Close your eyes when adjusting sliders"],
  },
  {
    id: "site-execute",
    name: "Pro League Execute",
    description: "Plan and execute a coordinated site take with utility usage on a countdown.",
    side: "attack",
    difficulty: "hard",
    category: "tactical",
    restrictions: ["Coordinated utility dump", "Count down from 5"],
  },
  {
    id: "spawn-rush-defense",
    name: "Reverse Spawn Rush",
    description: "All defenders must push out and hunt attackers at spawn within 30 seconds.",
    side: "defense",
    difficulty: "extreme",
    category: "meme",
    restrictions: ["Rush attackers at spawn", "First 30 seconds"],
  },
  {
    id: "maestro-cam",
    name: "Evil Eye Only",
    description: "Maestro cannot use his gun. Must get kills with Evil Eye lasers only.",
    side: "defense",
    difficulty: "extreme",
    category: "challenge",
    restrictions: ["Maestro required", "Evil Eye kills only"],
  },
  {
    id: "echo-denial",
    name: "Echo Chamber",
    description: "Echo must deny the plant using Yokai drones. No gun kills allowed for Echo.",
    side: "defense",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Echo required", "Yokai denial only"],
  },
  {
    id: "all-speed-3",
    name: "Speedy Squad",
    description: "Everyone must play 3-speed operators only.",
    side: "both",
    difficulty: "easy",
    category: "fun",
    restrictions: ["3-speed operators only"],
  },
  {
    id: "all-speed-1",
    name: "Heavy Hitters",
    description: "Everyone must play 1-speed operators only.",
    side: "both",
    difficulty: "medium",
    category: "fun",
    restrictions: ["1-speed operators only"],
  },
  {
    id: "drone-peek",
    name: "Drone Peek Protocol",
    description: "Must drone every single room before entering. No exceptions.",
    side: "attack",
    difficulty: "medium",
    category: "tactical",
    restrictions: ["Drone every room", "No dry peeks"],
  },
  {
    id: "clutch-or-kick",
    name: "Clutch or Kick",
    description: "If you're the last alive, you must clutch the round or get kicked from the squad (jokingly).",
    side: "both",
    difficulty: "hard",
    category: "meme",
    restrictions: ["Last alive must win"],
  },
  {
    id: "call-your-shot",
    name: "Called Shot",
    description: "Must announce which body part you're aiming for before each kill.",
    side: "both",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Call your shot before firing"],
  },
  {
    id: "buddy-system",
    name: "Buddy System",
    description: "Pair up with a teammate. You can never be more than 5 meters apart.",
    side: "both",
    difficulty: "medium",
    category: "teamwork",
    restrictions: ["Stay with your buddy", "Max 5m apart"],
  },
  {
    id: "thermite-rush",
    name: "Thermite Rush",
    description: "Thermite must breach a reinforced wall within 45 seconds of round start.",
    side: "attack",
    difficulty: "hard",
    category: "challenge",
    restrictions: ["Thermite required", "Breach within 45 seconds"],
    tips: ["Rush Thatcher or Kali for support"],
  },
];

export function getRandomStrategy(side?: "attack" | "defense" | "both"): Strategy {
  let filtered = strategies;

  if (side && side !== "both") {
    filtered = strategies.filter(s => s.side === side || s.side === "both");
  }

  return filtered[Math.floor(Math.random() * filtered.length)];
}

export function getStrategiesBySide(side: "attack" | "defense" | "both"): Strategy[] {
  if (side === "both") return strategies;
  return strategies.filter(s => s.side === side || s.side === "both");
}

export function getStrategiesByDifficulty(difficulty: Strategy["difficulty"]): Strategy[] {
  return strategies.filter(s => s.difficulty === difficulty);
}

export function getStrategiesByCategory(category: Strategy["category"]): Strategy[] {
  return strategies.filter(s => s.category === category);
}
